version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - restore_cache:
          key: maven-m2-repository
      - run: mvn clean package -DskipTests
      - save_cache:
          key: maven-m2-repository
          paths:
            - ~/.m2/repository
      - save_cache:
          key: hairspray-target
          paths:
            - target
            - core/target
            - jpa/target
  test:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - restore_cache:
          key: maven-m2-repository
      - restore_cache:
          key: hairspray-target
      - run: mvn test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
